# Generated by Django 4.2.7 on 2023-12-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userwallet'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
