# Generated by Django 4.2.7 on 2023-12-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(null=True, verbose_name='Прошел модерацию'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Профинансирован', 'funded'), ('В процесе финансирования', 'in_progress'), ('Отменен', 'cancelled'), ('На модерации', 'on_moderation')], verbose_name='Статус'),
        ),
    ]
